name: note_app
description: Simple note taking application developed with TDD
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.2
  path_provider: ^2.0.15
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  build_runner: ^2.4.6
  dartz: ^0.10.1
  hive: ^2.2.3
  logger: ^1.4.0
  mockito: ^5.4.2
  hive_flutter: ^1.1.0
  connectivity: ^3.0.6
  test: ^1.24.1
  bloc: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true